version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: voice_agent_postgres
    environment:
      POSTGRES_DB: voice_agent_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - voice_agent_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: voice_agent_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - voice_agent_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voice_agent_backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/voice_agent_db
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - postgres
      - redis
    networks:
      - voice_agent_network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voice_agent_frontend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - voice_agent_network
    restart: unless-stopped

  # MinIO for S3-compatible storage (development)
  minio:
    image: minio/minio
    container_name: voice_agent_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - voice_agent_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: voice_agent_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - voice_agent_network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  voice_agent_network:
    driver: bridge